### ISSUE TITLE
/ntf/bmv2/../../switch/configure: not found

### ISSUE THREAD

**Issue by JasonTang1992** [p4lang/ntf#4]
I running the shell script run_build_for_ptf.sh, and it report error:
`./run_build_for_ptf.sh: line 35: cd: /home/jason/workspace/ntf/bmv2/../../switch: No such file or directory
./run_build_for_ptf.sh: line 37: ./autogen.sh: No such file or directory
./run_build_for_ptf.sh: line 40: /home/jason/workspace/ntf/bmv2/../../switch/configure: No such file or directory
`
There are no dir called "switch" in the workspace..

**Comment by herlenashavi** [comment]
Jason,
Please use the p4lang [switch](https://github.com/p4lang/switch) repo to run the tests. The branch of NTF you are trying to run these tests from is outdated.

Thanks
