### ISSUE TITLE
ERROR::Cloning into 'switch'...

### ISSUE THREAD

**Issue by zenhox** [p4lang/ntf#7]
hox@ubuntu:~/workspace/INT/ntf-int-demo$ ./pull_modules.sh
.....
....
Cloning into 'switch'...
Warning: Permanently added the RSA host key for IP address '13.250.177.223' to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.
-------------------------------------------------------------------------------------------------------------
How can I solve this issue?

**Comment by zenhox** [comment]
It seems that remote repository is not exists.

**Comment by AmazingBJ** [comment]
> It seems that remote repository is not exists.

hi,I met the same issue.If I don't pull this repository, will it affect my follow-up work?How do you fix this problem.Thanks~~~

**Comment by AmazingBJ** [comment]
> 

你好，我才看见你也是中国人。。。那后续不拉这个东西的话影响复现不兄弟，很急，盼回复谢谢~~

**Comment by zenhox** [comment]
应该是有影响的，这都好多年了，早忘记了。我当时也没解决，不建议使用这个仓库，都5年没更新了。。。类似的功能找找最近的吧。

**Comment by AmazingBJ** [comment]
> 应该是有影响的，这都好多年了，早忘记了。我当时也没解决，不建议使用这个仓库，都5年没更新了。。。类似的功能找找最近的吧。

兄弟，那你还找到过有关于int的demo吗

**Comment by zenhox** [comment]
感觉这么多年过去了，在github搜一搜，应该有很多呀。而且这东西自己写个demo也并不复杂。你参考下这些：https://github.com/tatry/INT-BMv2
https://github.com/leandrocalmeida/P4
我刚刚随便搜了下。

**Comment by AmazingBJ** [comment]
> 感觉这么多年过去了，在github搜一搜，应该有很多呀。而且这东西自己写个demo也并不复杂。你参考下这些：https://github.com/tatry/INT-BMv2 https://github.com/leandrocalmeida/P4 我刚刚随便搜了下。

感谢您，主要是我自己并没有任何p4语言的基础，就看了看那个官方联系也不咋会写，您这有p4语言的学习资料吗，麻烦您了
